import { API_CONFIG, apiPost } from '@/config/api'

export interface AIMessage {
  readonly role: 'user' | 'assistant' | 'system'
  readonly content: string
}

export interface AIChatRequest {
  readonly messages: AIMessage[]
  readonly context?: string
}

export interface AIChatResponse {
  readonly message: string
  readonly suggestions?: string[]
}

export interface ContractGenerationRequest {
  readonly description: string
  readonly type: 'token' | 'nft' | 'defi' | 'dao' | 'custom'
  readonly features?: string[]
}

export interface ContractGenerationResponse {
  readonly contract: string
  readonly explanation: string
  readonly warnings?: string[]
  readonly suggestions?: string[]
}

export interface CodeReviewRequest {
  readonly code: string
  readonly language: 'solidity' | 'typescript' | 'javascript'
}

export interface CodeReviewResponse {
  readonly issues: ReviewIssue[]
  readonly score: number
  readonly summary: string
  readonly suggestions: string[]
}

export interface ReviewIssue {
  readonly severity: 'critical' | 'high' | 'medium' | 'low' | 'info'
  readonly title: string
  readonly description: string
  readonly line?: number
  readonly recommendation: string
}

export interface SecurityAuditRequest {
  readonly code: string
  readonly contractName: string
}

export interface SecurityAuditResponse {
  readonly issues: SecurityIssue[]
  readonly score: number
  readonly summary: string
  readonly recommendations: string[]
}

export interface SecurityIssue {
  readonly severity: 'critical' | 'high' | 'medium' | 'low'
  readonly category: string
  readonly title: string
  readonly description: string
  readonly line?: number
  readonly fix?: string
}

export interface TestGenerationRequest {
  readonly code: string
  readonly contractName: string
}

export interface TestGenerationResponse {
  readonly tests: string
  readonly explanation: string
  readonly coverage: string[]
}

export interface GasOptimizationRequest {
  readonly code: string
}

export interface GasOptimizationResponse {
  readonly suggestions: OptimizationSuggestion[]
  readonly estimatedSavings: string
}

export interface OptimizationSuggestion {
  readonly line: number
  readonly issue: string
  readonly suggestion: string
  readonly impact: 'high' | 'medium' | 'low'
}

/**
 * AI Service for NorStudio
 */
export class AIService {
  /**
   * Send a chat message to AI assistant
   */
  static async chat(request: AIChatRequest): Promise<AIChatResponse> {
    try {
      const response = await apiPost<AIChatResponse>(
        API_CONFIG.endpoints.ai.chat,
        request
      )
      return response
    } catch (error) {
      console.error('AI Chat Error:', error)
      // Return mock response for development
      return {
        message: "I'm here to help! I can assist you with writing smart contracts, reviewing code, and optimizing gas usage. What would you like to work on?",
        suggestions: [
          'Generate an ERC-20 token',
          'Review my contract for security issues',
          'Optimize gas usage',
          'Generate test cases',
        ],
      }
    }
  }

  /**
   * Generate a smart contract from natural language description
   */
  static async generateContract(
    request: ContractGenerationRequest
  ): Promise<ContractGenerationResponse> {
    try {
      const response = await apiPost<ContractGenerationResponse>(
        API_CONFIG.endpoints.ai.generateContract,
        request
      )
      return response
    } catch (error) {
      console.error('Contract Generation Error:', error)
      // Return mock response for development
      return {
        contract: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract GeneratedContract {
    // Generated based on: ${request.description}
    // TODO: Implement contract logic
}`,
        explanation: 'This is a basic contract structure. In production, this would be generated by AI based on your description.',
        warnings: ['This is a development placeholder'],
        suggestions: ['Add access control', 'Implement events', 'Add documentation'],
      }
    }
  }

  /**
   * Review code for quality and best practices
   */
  static async reviewCode(request: CodeReviewRequest): Promise<CodeReviewResponse> {
    try {
      const response = await apiPost<CodeReviewResponse>(
        API_CONFIG.endpoints.ai.explainCode,
        request
      )
      return response
    } catch (error) {
      console.error('Code Review Error:', error)
      // Return mock response for development
      return {
        issues: [
          {
            severity: 'medium',
            title: 'Missing Input Validation',
            description: 'Function parameters should be validated',
            line: 10,
            recommendation: 'Add require() statements to validate inputs',
          },
          {
            severity: 'low',
            title: 'Missing NatSpec Documentation',
            description: 'Functions should have NatSpec comments',
            recommendation: 'Add /// @notice and /// @param documentation',
          },
        ],
        score: 75,
        summary: 'Code is generally good but could benefit from additional validation and documentation.',
        suggestions: [
          'Add input validation',
          'Include NatSpec documentation',
          'Consider adding events',
        ],
      }
    }
  }

  /**
   * Perform security audit on smart contract
   */
  static async auditContract(
    request: SecurityAuditRequest
  ): Promise<SecurityAuditResponse> {
    try {
      const response = await apiPost<SecurityAuditResponse>(
        API_CONFIG.endpoints.ai.auditContract,
        request
      )
      return response
    } catch (error) {
      console.error('Security Audit Error:', error)
      // Return mock response for development
      return {
        issues: [
          {
            severity: 'high',
            category: 'Access Control',
            title: 'Missing Access Restrictions',
            description: 'Critical functions lack proper access control',
            line: 15,
            fix: 'Add onlyOwner or role-based modifiers',
          },
          {
            severity: 'medium',
            category: 'Reentrancy',
            title: 'Potential Reentrancy Vulnerability',
            description: 'External calls before state updates',
            line: 25,
            fix: 'Follow checks-effects-interactions pattern',
          },
        ],
        score: 65,
        summary: 'Contract has some security concerns that should be addressed before deployment.',
        recommendations: [
          'Add access control modifiers',
          'Implement reentrancy guards',
          'Add emergency pause functionality',
          'Consider using OpenZeppelin libraries',
        ],
      }
    }
  }

  /**
   * Generate test cases for smart contract
   */
  static async generateTests(
    request: TestGenerationRequest
  ): Promise<TestGenerationResponse> {
    try {
      const response = await apiPost<TestGenerationResponse>(
        API_CONFIG.endpoints.ai.suggestTests,
        request
      )
      return response
    } catch (error) {
      console.error('Test Generation Error:', error)
      // Return mock response for development
      return {
        tests: `import { expect } from "chai";
import { ethers } from "hardhat";

describe("${request.contractName}", function () {
  it("Should deploy successfully", async function () {
    const Contract = await ethers.getContractFactory("${request.contractName}");
    const contract = await Contract.deploy();
    await contract.deployed();
    expect(contract.address).to.be.properAddress;
  });

  // Additional tests would be generated here
});`,
        explanation: 'Generated comprehensive test suite covering deployment and basic functionality.',
        coverage: ['Deployment', 'Basic functions', 'Edge cases'],
      }
    }
  }

  /**
   * Get gas optimization suggestions
   */
  static async optimizeGas(
    request: GasOptimizationRequest
  ): Promise<GasOptimizationResponse> {
    try {
      // In production, this would call the API
      return {
        suggestions: [
          {
            line: 12,
            issue: 'Using uint256 when uint128 would suffice',
            suggestion: 'Change to uint128 to save storage costs',
            impact: 'medium',
          },
          {
            line: 20,
            issue: 'Multiple SLOAD operations',
            suggestion: 'Cache storage variable in memory',
            impact: 'high',
          },
        ],
        estimatedSavings: '~30% gas reduction',
      }
    } catch (error) {
      console.error('Gas Optimization Error:', error)
      throw error
    }
  }

  /**
   * Explain code in natural language
   */
  static async explainCode(code: string): Promise<string> {
    try {
      const response = await apiPost<{ explanation: string }>(
        API_CONFIG.endpoints.ai.explainCode,
        { code }
      )
      return response.explanation
    } catch (error) {
      console.error('Code Explanation Error:', error)
      return 'This code snippet contains smart contract logic. In production, AI would provide a detailed explanation.'
    }
  }
}
